### ISSUE TITLE
how to change time period from every1 min to every 15 sec?

### ISSUE THREAD

**Issue by vpaulos** [thecode/ha-onewire-sysbus#288]

**Comment by thecode** [comment]
Integrations using config flow are not allowed to set scan interval.
You can disable automatic polling and make your own automation with any rate you want (you are responsible for not overloading your system).

Examples:
https://community.home-assistant.io/t/add-scan-interval-to-fronius-integration/296872/11?u=thecode
https://github.com/home-assistant/core/issues/83565#issuecomment-1345250762
