### ISSUE TITLE
Documentation Readme addition to install integration?

### ISSUE THREAD

**Issue by sinusoidal-zz** [thecode/ha-onewire-sysbus#58]
Probably just me being a newb, but the documentation readme on https://github.com/thecode/ha-onewire-sysbus doesn't actually end with 'now add/install 1Wire-sysbus integration' on the front end as a final step.  It just seems to suggest that 'on boot' the devices will be available/visible in dev tools.  Confused me a bit but all working now.

**Comment by thecode** [comment]
Thanks, I will update the docs to include this step
