### ISSUE TITLE
Bad sensor name on arm64 arch

### ISSUE THREAD

**Issue by plop3** [thecode/ha-onewire-sysbus#77]
Hello,
It seems there is a problem with the arm64 architecture.
The 1wire sensors are well found.
But their name doesn't seem correct and they don't report any temperature values.
Ex: sensor 10.8CD1CB020800 is named in home assistant 10-000802cbd18c (numbers are reversed).

         "manufacturer": "Maxim Integrated",
         "model": "10",
         "name": "10-000802cbd18c"

Tested with 1wire integration (owserver on an another computer), i have: sensor.10_8cd1cb020800_temperature

**Comment by equinoxe12** [comment]
I have same problem with HA
